import {
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconArrowDownToArc,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsLeftRight,
  IconArrowUpToArc,
  IconBox,
  IconBraces,
  IconCircle,
  IconCloudCheck,
  IconCornerDownLeft,
  IconCornerDownRight,
  IconCornerUpLeft,
  IconCornerUpRight,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFlipHorizontal,
  IconFlipVertical,
  IconFolder,
  IconGridDots,
  IconHash,
  IconLayersLinked,
  IconLock,
  IconLockOpen,
  IconMaximize,
  IconPencil,
  IconPhoto,
  IconQrcode,
  IconRotate,
  IconRotateClockwise,
  IconRuler,
  IconSettings,
  IconShape,
  IconDeviceMobile,
  IconSparkles,
  IconSquare,
  IconSquareDashed,
  IconTypography,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconTools,
  IconX,
  IconZoomIn,
  IconZoomOut,
  IconDeviceDesktop,
  IconLayoutSidebar,
} from '@tabler/icons-react';
import type { Icon } from '@tabler/icons-react';

export const TABLER_GLYPHS: Record<string, Icon> = {
  alignCenter: IconAlignCenter,
  alignLeft: IconAlignLeft,
  alignRight: IconAlignRight,
  arrowDown: IconArrowDownToArc,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  arrowUp: IconArrowUpToArc,
  arrows: IconArrowsLeftRight,
  boxes: IconBox,
  braces: IconBraces,
  circle: IconCircle,
  cloudCheck: IconCloudCheck,
  cornerBottomLeft: IconCornerDownLeft,
  cornerBottomRight: IconCornerDownRight,
  cornerTopLeft: IconCornerUpLeft,
  cornerTopRight: IconCornerUpRight,
  eye: IconEye,
  eyeOff: IconEyeOff,
  file: IconFile,
  flipH: IconFlipHorizontal,
  flipV: IconFlipVertical,
  folder: IconFolder,
  grid: IconGridDots,
  group: IconHash,
  image: IconPhoto,
  layers: IconLayersLinked,
  lock: IconLock,
  lockOpen: IconLockOpen,
  maximize: IconMaximize,
  monitor: IconDeviceDesktop,
  panelLeft: IconLayoutSidebar,
  pencil: IconPencil,
  'qr-code': IconQrcode,
  rect: IconSquare,
  redo: IconArrowForwardUp,
  rotateLeft: IconRotate,
  rotateRight: IconRotateClockwise,
  ruler: IconRuler,
  settings: IconSettings,
  shapes: IconShape,
  smartphone: IconDeviceMobile,
  sparkles: IconSparkles,
  square: IconSquare,
  'square-dashed': IconSquareDashed,
  margins: IconSquareDashed,
  text: IconTypography,
  tools: IconTools,
  type: IconTypography,
  undo: IconArrowBackUp,
  wrench: IconTools,
  x: IconX,
  'zoom-in': IconZoomIn,
  'zoom-out': IconZoomOut,
};
