import { defineConfig } from 'oxlint';
import core from 'ultracite/oxlint/core';
import react from 'ultracite/oxlint/react';

export default defineConfig({
  extends: [core, react],
  ignorePatterns: [
    ...core.ignorePatterns,
    '**/routeTree.gen.ts',
    '**/routes/__root.tsx',
    'packages/typescript-config/tsup.library.d.ts',
    'packages/typescript-config/tsup.library.js',
  ],
  rules: {
    'class-methods-use-this': 'off',
    'prefer-destructuring': 'off',
    'promise/prefer-await-to-callbacks': 'off',
    'promise/prefer-await-to-then': 'off',
    'require-await': 'off',
    'sort-keys': 'off',
    'func-style': 'off',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-invalid-void-type': 'off',
    'typescript/no-explicit-any': 'off',
    'typescript/no-dynamic-delete': 'off',
    'typescript/prefer-for-of': 'off',
    'typescript/consistent-type-imports': 'off',
    'eslint/complexity': 'off',
    'eslint/no-warning-comments': 'off',
    'eslint/no-negated-condition': 'off',
    'eslint/no-nested-ternary': 'off',
    'unicorn/no-nested-ternary': 'off',
    'eslint/no-use-before-define': 'off',
    'eslint/prefer-named-capture-group': 'off',
    'eslint/require-unicode-regexp': 'off',
    'eslint/prefer-promise-reject-errors': 'off',
    'eslint/no-inline-comments': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-reduce': 'off',
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-add-event-listener': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/no-lonely-if': 'off',
    'unicorn/no-this-assignment': 'off',
    'unicorn/prefer-export-from': 'off',
    'unicorn/prefer-number-coercion': 'off',
    'unicorn/prefer-single-call': 'off',
    'oxc/no-barrel-file': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
    'eslint/max-classes-per-file': 'off',
    'typescript/parameter-properties': 'off',
    'typescript/method-signature-style': 'off',
    'promise/avoid-new': 'off',
    'eslint/no-await-in-loop': 'off',
    'jsx-a11y/prefer-tag-over-role': 'off',
    'jsx-a11y/label-has-associated-control': 'off',
    'eslint/no-empty-function': 'off',
    'import/consistent-type-specifier-style': 'off',
    'react/display-name': 'off',
    'react/no-danger': 'off',
    'react/hook-use-state': 'off',
    'react/react-compiler': 'off',
    'jsdoc/require-param-description': 'off',
    'github/filenames-match-regex': 'off',
    'github/no-inner-html': 'off',
    'github/no-then': 'off',
    'sonarjs/cognitive-complexity': 'off',
    'sonarjs/destructuring-assignment-syntax': 'off',
    'sonarjs/expression-complexity': 'off',
    'sonarjs/max-union-size': 'off',
    'sonarjs/no-all-duplicated-branches': 'off',
    'sonarjs/no-collapsible-if': 'off',
    'sonarjs/no-duplicate-string': 'off',
    'sonarjs/no-identical-functions': 'off',
    'sonarjs/no-nested-conditional': 'off',
    'sonarjs/no-nested-functions': 'off',
    'sonarjs/no-undefined-assignment': 'off',
    'sonarjs/no-unused-function-argument': 'off',
    'sonarjs/redundant-type-aliases': 'off',
    'sonarjs/too-many-break-or-continue-in-loop': 'off',
    'sonarjs/use-type-alias': 'off',
    'react-doctor/async-await-in-loop': 'off',
    'react-doctor/js-combine-iterations': 'off',
    'react-doctor/js-flatmap-filter': 'off',
    'react-doctor/js-index-maps': 'off',
    'react-doctor/no-adjust-state-on-prop-change': 'off',
    'react-doctor/no-array-index-as-key': 'off',
    'react-doctor/no-derived-state': 'off',
    'react-doctor/no-derived-state-effect': 'off',
    'react-doctor/no-event-handler': 'off',
    'react-doctor/no-giant-component': 'off',
    'react-doctor/no-pass-data-to-parent': 'off',
    'react-doctor/no-prop-callback-in-effect': 'off',
    'react-doctor/react-compiler-no-manual-memoization': 'off',
    'react-doctor/server-sequential-independent-await': 'off',
  },
});
