import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRightToLine,
  ArrowUpToLine,
  Boxes,
  Circle,
  CornerDownLeft,
  CornerDownRight,
  CornerUpLeft,
  CornerUpRight,
  File,
  FlipHorizontal2,
  FlipVertical2,
  Folder,
  Grid3x3,
  Hash,
  Image,
  Layers,
  Lock,
  LockOpen,
  Redo2,
  RotateCcw,
  RotateCw,
  Settings,
  Shapes,
  Sparkles,
  Square,
  Type,
  Undo2,
  Wrench,
  X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const LUCIDE_GLYPHS: Record<string, LucideIcon> = {
  alignCenter: AlignCenter,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  arrowDown: ArrowDownToLine,
  arrowLeft: ArrowLeftToLine,
  arrowRight: ArrowRightToLine,
  arrowUp: ArrowUpToLine,
  arrows: ArrowLeftRight,
  boxes: Boxes,
  circle: Circle,
  cornerBottomLeft: CornerDownLeft,
  cornerBottomRight: CornerDownRight,
  cornerTopLeft: CornerUpLeft,
  cornerTopRight: CornerUpRight,
  file: File,
  flipH: FlipHorizontal2,
  flipV: FlipVertical2,
  folder: Folder,
  grid: Grid3x3,
  group: Hash,
  image: Image,
  layers: Layers,
  lock: Lock,
  lockOpen: LockOpen,
  rect: Square,
  redo: Redo2,
  rotateLeft: RotateCcw,
  rotateRight: RotateCw,
  settings: Settings,
  shapes: Shapes,
  sparkles: Sparkles,
  square: Square,
  text: Type,
  tools: Wrench,
  type: Type,
  undo: Undo2,
  wrench: Wrench,
  x: X,
};
